[dataset]
filename = "./dataset/train.txt"

[dataloader.train]
batch_size = 256 # 2**8
shuffle = true
drop_last = true

[dataloader.test]
batch_size = 2048

[model]
embedding_dim = 26
k = 10

[trainer]
epochs = 20
learning_rate = 1e-4
weight_decay = 1e-6
